### ISSUE TITLE
HostFactory Plugin for Kubernetes: Design Proposal

### ISSUE THREAD

**Issue by fgogolli** [morganstanley/symphony-hostfactory#18]
# HostFactory Plugin for Kubernetes: Design Proposal

This document is a design proposal for implementing a HostFactory Plugin for Kubernetes using the native [Operator/Controller](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) pattern. The document includes descriptions of the architecture and the flow of API calls and the different components invloved, as well as some examples of how the configuration/Kubernetes spec for the resources may look like. Any and all parts of this proposal can be adjusted as needed to implement additional functionality as required.

## Current Design and Flow

Below is the current end-to-end flow of the project and components, as currently implemented. In addition to that, the document also includes a flow that uses the native Kubernetes API to create pods, however, this was decided against, due to the potential runtime synchronous dependencies and timeouts that may occur.  

### Current Flow

Below is the current end-to-end flow of the project and its components:

```mermaid
sequenceDiagram
    participant Admin as hostfactory-admin
    participant HF as hostfactory
    participant FS as filesystem
    participant W as watcher
    participant K as kubernetes

    Admin->>HF: requestMachines(template)
    HF->>FS: Write to $WORKDIR/requests
    FS->>W: Inotify on $WORKDIR/requests
    W->>K: POST pod objects
    K-->>W: Returns object id
    K->>FS: Kube event
    FS->>W: Write to $WORKDIR/pods

    Admin->>HF: getRequestStatus
    HF->>FS: Read from $WORKDIR/pods
    FS-->>HF: Return pods status
    HF-->>Admin: Return request status
```

### HostFactory and Kubernetes Native Flow

Below is a diagram of an end-to-end implementation of the HostFactory Plugin, that aligns with the Hostfactory Plugin APIs and makes synchronous calls to the Kubernetes API to create pods per each request.

```mermaid
sequenceDiagram
    participant Admin as hostfactory-admin
    participant HF as hostfactory
    participant K as kubernetes

    Admin->>HF: requestMachines(template)
    Note over Admin,HF: {"template": "Template-K8s-A", "machineCount": 1}
    HF->>K: POST pod objects
    K-->>HF: Returns object id
    HF-->>Admin: json response
    Note over HF,Admin: {"message": "Request successful", "requestId": "f0d97275-dce2-4f22-94a4-44717e802b97"}

    Admin->>HF: getRequestStatus
    Note over Admin,HF: {"requests": {"requestId": "f0d97275-dce2-4f22-94a4-44717e802b97"}}
    HF->>K: GET pod objects
    K-->>HF: Return pod status
    HF-->>Admin: symphony json
    Note over HF,Admin: {"requests": {"requestId": "f0d97275-dce2-4f22-94a4-44717e802b97", "status": "complete", "machines": [...]}}
```

## Proposed Design and Flows

The proposed design aligns the end-to-end implementation with the existing patterns and functionality of the different tools and components involved. The proposed changes to the HostFactory plugin ensure that the Kubernetes plugin will align and work similarly to how the rest of the HostFactory Plugin ecosystem works and also ensures we deploy and manage it the same way as we do other plugins. Similarly, by adopting the Kubernetes native operator/controller pattern, we achieve the same design tenet of separating the responsibility of creating, managing the lifecycle and deletion of machines/pods through watchers, while decoupling them from the plugin itself. This ensures that we follow the intended principles of this project, while also following the same deployment and runtime flow of the services used.

When it comes to state management, instead of using the filesystem as a database, we now move to having the relevant state witht he relevant information for each of the components. The HostFactory plugin would use a regular format for its database, ie a JSON file, like the other plugins do, and maps the requests and templates to the relevant Kubernetes custom resource. And the HostFactory Operator would then use etcd, like any other controller, to store and update the state of the resources that it manages.

### Architecture Overview

The end-to-end system would consist of three main layers that work together to manage resource provisioning. Each layer has specific responsibilities and components that interact through well-defined interfaces.

1. **Initial Request**
   - Client schedules jobs onto the Symphony cluster using the Symphony API.
   - Requestor plugin notices the running jobs/applications and computes the resources needed for them.
   - If more/less resources are required, then Requestor plugin then sends these requests to HostFactory.

2. **HostFactory Processing**
   - HostFactory receives the request and calls the appropriate HostFactory Plugin API.
   - Plugin creates the corresponding [Kubernetes Custom Resources (CRs)](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) with required specifications:
     - Pod specifications from defined templates.
     - Machine count and naming conventions.
     - Required labels and annotations for tracking if needed.
     - List of machines to be returned, if resources are not needed anymore.

3. **Kubernetes Orchestration**
   - HostFactory Operator monitors for new Custom Resources based on the defined Custom Resource Definitions (examples below).
   - Operator creates or deletes pods based on the request type (RequestMachines or RequestReturnMachines).
   - Cluster Autoscaler (CAS)/Karpenter handles node provisioning as needed by calling the Cloud Provider APIs.
   - Kubernetes Scheduler assigns pods to available nodes (as a simplification of the full flow).

4. **Status Management**
   - Operator maintains detailed status information about the pods/machines it manages, including:
     - Machine IDs, names and network addresses.
     - Launch times and current states.
     - Spot instance termination notifications and how they affect t he status of Pods/Machines.
     - Request completion status, ie if all pods are provisioned on a request or deleted on a return.

```mermaid
flowchart TD
    subgraph Symphony
        S[Symphony] -->|request resources| RP[Requestor Plugin]
        RP -->|request machines| HF[HostFactory]
    end
    
    subgraph HostFactory Plugin
        HF -->|HF Plugin APIs| HP[HostFactory Plugin]
    end
    
    subgraph Kubernetes
        HP -->|create/update CRs| K[Kubernetes API]
        K -->|watch events| O[HostFactory Operator]
        
        subgraph Resources
            P[Pods]
            N[Nodes]
        end
        
        O -->|create/delete| P
        K -->|pending pods| CAS[CAS/Karpenter]
        CAS -->|provision/deprovision| N
        KS[Kube Scheduler] -->|schedule| P
        KS -.->|to| N
    end
```

### RequestMachines Flow

Below is a description of the RequestMachines API flow:

1. **Request Initiation**
   - HostFactory calls the plugin's requestMachines API with:
     - The templateId, which includes the complete pod specification for machine creation, based on the defined templates of the plugin.
     - Number of machines required.
     - Name prefix for request identification (to name pods with predictable names, but also be able to identify/link them to specific requests).
     - Optional labels and annotations for tracking/linking pods to requests.

2. **Resource Creation**
   - Plugin creates RequestMachines CR with provided specifications.
   - Operator detects a new CR object by watching the relevant API and creates the pods for that request with:
     - Specified name prefix for identification.
     - Required labels/annotations.
     - Full pod specification from request.

3. **Node Provisioning**
   - CAS/Karpenter detects pending pods.
   - Provisions new nodes based on pod requirements by calling the Cloud Provider APIs.
   - Kubernetes Scheduler assigns pods to nodes.

4. **Status Management**
   - Operator updates CR status with:
     - Machine IDs, names and hostnames.
     - IP addresses (private and public).
     - Launch times and current states.
     - Status updates (executing, succeed, fail).
     - Spot instance termination notifications (gracePeriod).
   - HostFactory polls status using getRequestStatus API.
   - Plugin retrieves and returns current status from the CR (running, complete, complete_with_error).

#### RequestMachines Flow Diagram:

```mermaid
sequenceDiagram
    participant HF as HostFactory
    participant Plugin as HostFactory Plugin
    participant K8s as Kubernetes API
    participant Operator as HostFactory Operator
    participant CAS as CAS/Karpenter
    participant Scheduler as Kube Scheduler
    
    HF->>Plugin: requestMachines(podSpec, count, namePrefix)
    Plugin->>K8s: Create RequestMachines CR
    K8s-->>Plugin: CR Created
    Plugin-->>HF: Return Request ID
    
    K8s->>Operator: Watch Event
    Operator->>K8s: Create Pods with Prefix
    K8s->>CAS: Detect Pending Pods
    CAS->>K8s: Provision Nodes
    K8s->>Scheduler: Schedule Pods to Nodes
    
    Operator->>K8s: Update CR Status
    
    HF->>Plugin: getRequestStatus(requestId)
    Plugin->>K8s: Get RequestMachines CR
    K8s-->>Plugin: Return Current Status
    Plugin-->>HF: Return Status
```

### RequestReturnMachines Flow

Below is a description of the RequestReturnMachines API flow:

1. **Return Request Initiation**
   - HostFactory calls the plugin's requestReturnMachines API with:
     - List of machine names to be returned.

2. **Resource Cleanup**
   - Plugin creates RequestReturnMachines CR with machine list.
   - Operator detects new CR and initiates the deletion of the individual pods from that list.
   - Kubernetes removes the pods from the nodes.

3. **Node Scaling**
   - After pod removal, CAS/Karpenter evaluates node utilization based on configuration.
   - If nodes are underutilized, CAS/Karpenter may trigger node removal.
   - Node removal occurs only if no other pods require the resources.

4. **Status Tracking**
   - Operator updates RequestReturnMachines CR status with:
     - Individual machine status (executing, succeed, fail).
     - Overall request status (running, complete, complete_with_error).
   - HostFactory polls status using getRequestStatus API.
   - Plugin retrieves and returns current status from the CR (running, complete, complete_with_error).

#### RequestReturnMachines Flow Diagram:

```mermaid
sequenceDiagram
    participant HF as HostFactory
    participant Plugin as HostFactory Plugin
    participant K8s as Kubernetes API
    participant Operator as HostFactory Operator
    participant CAS as CAS/Karpenter
    
    HF->>Plugin: requestReturnMachines(machineList)
    Plugin->>K8s: Create RequestReturnMachines CR
    K8s-->>Plugin: CR Created
    Plugin-->>HF: Return Return Request ID
    
    K8s->>Operator: Watch Event
    Operator->>K8s: Delete Pods
    K8s->>CAS: Scale Down (if needed)
    
    Operator->>K8s: Update CR Status
    
    HF->>Plugin: getRequestStatus(returnRequestId)
    Plugin->>K8s: Get RequestReturnMachines CR
    K8s-->>Plugin: Return Current Status
    Plugin-->>HF: Return Status
```
## Custom Resource Definitions (CRDs)

Below are some examples of how the HostFactory plugin specific Custom Resource Definitions (CRDs) may look like for this implementation.

### RequestMachines CRD

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: requestmachines.hostfactory.symphony.ibm.com
spec:
  group: hostfactory.symphony.ibm.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                podSpec:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  description: "Full Kubernetes pod specification for machine creation"
                count:
                  type: integer
                  description: "Number of machines to provision"
                namePrefix:
                  type: string
                  description: "Prefix for pod names to identify request association"
                labels:
                  type: object
                  additionalProperties:
                    type: string
                annotations:
                  type: object
                  additionalProperties:
                    type: string
            status:
              type: object
              properties:
                status:
                  type: string
                  enum: [running, complete, complete_with_error]
                  description: "Overall request status"
                message:
                  type: string
                  description: "Additional status information"
                machines:
                  type: array
                  items:
                    type: object
                    properties:
                      machineId:
                        type: string
                        description: "ID of the machine from provider"
                      name:
                        type: string
                        description: "Host name of the machine"
                      result:
                        type: string
                        enum: [executing, fail, succeed]
                      status:
                        type: string
                        enum: [running, stopped, terminated, shutting-down, stopping]
                      privateIpAddress:
                        type: string
                      publicIpAddress:
                        type: string
                      launchtime:
                        type: integer
                        description: "Launch time in seconds (UTC)"
                      message:
                        type: string
                      gracePeriod:
                        type: integer
                        description: "Seconds remaining before spot instance termination"
```

### RequestReturnMachines CRD

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: requestreturnmachines.hostfactory.symphony.ibm.com
spec:
  group: hostfactory.symphony.ibm.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                machines:
                  type: array
                  items:
                    type: string
                    description: "List of machine names to be returned"
            status:
              type: object
              properties:
                status:
                  type: string
                  enum: [running, complete, complete_with_error]
                message:
                  type: string
                machines:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      result:
                        type: string
                        enum: [executing, fail, succeed]
                      message:
                        type: string
```

## Operator Design & Frameworks

There are multiple tools that the Kubernetes community has developed, that aim in helping with the creation of new operators. Some examples include:

- [Operator Framework](https://operatorframework.io/)
- [KubeBuilder](https://github.com/kubernetes-sigs/kubebuilder)
- [MetaController](https://metacontroller.github.io/metacontroller/)
- [PyKube](https://pykube.readthedocs.io/en/latest/index.html)
- [Kubernetes Operator Pythonic Framework (Kopf)](https://github.com/nolar/kopf)

Of the above, the first two are meant to be used for Operators written in Go. Kopf is the only one that is purely Python based and targetting Python as a programming language. PyKube is a lightweight Python client library for Kubernetes and Kopf already uses it. Considering the requirements of the project, Kopf may be a good starting point for the development of the HostFactory Plugin Operator. That being said, an Operator Framework, like any other, is meant to help with the heavy lifting of the regular functionality that an operator needs (ie creating resources or watching for their status updates, etc.), however it **not** required. An operator can be fully implemented using the official [Kubernetes Python client](https://github.com/kubernetes-client/python).

### Operator Implementation in Python with Kopf

The recommended approach for implementing the HostFactory Operator is using the Kubernetes Operator Pythonic Framework (Kopf). Some resources for getting started:

1. [Kopf Documentation](https://kopf.readthedocs.io/)
2. [Kopf Tutorial](https://kopf.readthedocs.io/en/stable/walkthrough/creation/)
3. [Kopf Examples Repository](https://github.com/nolar/kopf/tree/main/examples)

### Operator Functions/Logic

Similar to the existing implementation, we will need to have several watchers which operate directly within the Kubernetes cluster and watch the relevant Kuberneter APIs for udpates and information. Below is a list of some of the watcher/functions - they can be combined as needed/desired:

1. **RequestMachines Handler**
   - Watch for new RequestMachines CRs
   - Create pods based on specifications
   - Update status as pods are created and become ready

2. **RequestReturnMachines Handler**
   - Watch for new RequestReturnMachines CRs
   - Initiate pod deletion for specified machines
   - Update status as pods are terminated

3. **Pod Lifecycle Management**
   - Monitor pod status changes
   - Update corresponding CR status
   - Handle pod failures and implement retry logic if/as needed.

4. **Spot Instance Management**
   - Integrate with node termination handler
   - Update pod status as would be affected by termination notices

5. **Status Reconciliation**
   - Periodically check and update CR status
   - Ensure consistency between actual state and reported state
